name:    compact-rpc-experiment
version:    0.1.0.0
license:    BSD3
author:     "Hiromi ISHII"
maintainer: "konn.jinro_at_gmail.com"
copyright:  "2022 (c) Hiromi ISHII"
description: Toy experiments on RPC with Compact Normal Form

extra-source-files:
- CHANGELOG.md
- README.md

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

dependencies:
- attoparsec
- base                  >=4.7 && <5
- binary
- bytestring
- containers
- compact
- generic-lens
- ghc-compact
- lens
- foldl
- network
- network-simple
- optparse-applicative
- rio
- stm
- streaming
- streaming-bytestring
- streaming-binary
- strict
- transformers
- unliftio
- unordered-containers
- vector

library:
  source-dirs: src

executables:
  compact-rpc:
    main:         Main.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - compact-rpc-experiment
